In [40]:
import numpy as np 

print(np.version.version)

1.18.5


In [41]:
a = np.random.random(size=[2,3,5])
a

array([[[0.60145568, 0.96862218, 0.54888616, 0.20650783, 0.30867614],
        [0.81252109, 0.06539481, 0.19172603, 0.39411952, 0.66584224],
        [0.56731364, 0.66285908, 0.57934718, 0.34615634, 0.49861224]],

       [[0.52609325, 0.33645248, 0.37591579, 0.79684611, 0.88565596],
        [0.66624973, 0.98165396, 0.91664637, 0.91598539, 0.79873488],
        [0.94945675, 0.11560273, 0.46218211, 0.5164583 , 0.32530057]]])

In [42]:
a = np.random.randint(0, 10000, size = (2,3,5))
a

array([[[1883, 4294, 1569, 7332, 6636],
        [4799, 5719, 7122, 9364, 1350],
        [8149, 1497, 6491, 3558,  111]],

       [[3419, 2913, 8572, 3502, 5732],
        [8496, 5267, 4307,    5, 9460],
        [6722, 3384, 5695, 7877, 3156]]])

In [43]:

b = np.ones((5,3,2))
b

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [44]:
print(a.shape == b.shape)

print(f'a shape = {a.shape} n b shape = {b.shape}')

False
a shape = (2, 3, 5) n b shape = (5, 3, 2)


In [45]:

"""

A numpy array uses vector algebra in that you can only add two arrays if they have the same dimensions as you are adding element by element

 a = [1,2,3,4,5]
 b = [1,1,1]
 a+b # will throw an error

whilst

 a = [1,2,3,4,5]
 b = [1,1,1,1,1]
 a+b # is ok

    https://stackoverflow.com/questions/40955903/simple-adding-two-arrays-using-numpy-in-python
    
    """

'\n\nA numpy array uses vector algebra in that you can only add two arrays if they have the same dimensions as you are adding element by element\n\n a = [1,2,3,4,5]\n b = [1,1,1]\n a+b # will throw an error\n\nwhilst\n\n a = [1,2,3,4,5]\n b = [1,1,1,1,1]\n a+b # is ok\n\n    https://stackoverflow.com/questions/40955903/simple-adding-two-arrays-using-numpy-in-python\n    \n    '

In [46]:
c = b.T
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [47]:
d = a+c


In [48]:

a


array([[[1883, 4294, 1569, 7332, 6636],
        [4799, 5719, 7122, 9364, 1350],
        [8149, 1497, 6491, 3558,  111]],

       [[3419, 2913, 8572, 3502, 5732],
        [8496, 5267, 4307,    5, 9460],
        [6722, 3384, 5695, 7877, 3156]]])

In [49]:
d
d.shape[1]

3

In [50]:
e = a * c

In [51]:
e

array([[[1.883e+03, 4.294e+03, 1.569e+03, 7.332e+03, 6.636e+03],
        [4.799e+03, 5.719e+03, 7.122e+03, 9.364e+03, 1.350e+03],
        [8.149e+03, 1.497e+03, 6.491e+03, 3.558e+03, 1.110e+02]],

       [[3.419e+03, 2.913e+03, 8.572e+03, 3.502e+03, 5.732e+03],
        [8.496e+03, 5.267e+03, 4.307e+03, 5.000e+00, 9.460e+03],
        [6.722e+03, 3.384e+03, 5.695e+03, 7.877e+03, 3.156e+03]]])

In [52]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()



In [53]:
f = np.empty((2,3,5))
f

array([[[1.883e+03, 4.294e+03, 1.569e+03, 7.332e+03, 6.636e+03],
        [4.799e+03, 5.719e+03, 7.122e+03, 9.364e+03, 1.350e+03],
        [8.149e+03, 1.497e+03, 6.491e+03, 3.558e+03, 1.110e+02]],

       [[3.419e+03, 2.913e+03, 8.572e+03, 3.502e+03, 5.732e+03],
        [8.496e+03, 5.267e+03, 4.307e+03, 5.000e+00, 9.460e+03],
        [6.722e+03, 3.384e+03, 5.695e+03, 7.877e+03, 3.156e+03]]])

In [60]:
for matrix in range(d.shape[0]):
    for row in range(d.shape[1]):
        for value in range(d.shape[2]):
            if d_min < d[matrix,row,value] < d_mean:
                f[matrix,row,value] = 25
            elif d_mean < d[matrix,row,value] < d_max:
                f[matrix, row, value] = 75
            elif d[matrix,row,value] == d_mean:
                
                f[matrix,row,value] = 50
                
            elif d[matrix,row,value] == d_min:
                
                f[matrix,row,value] = 0
            elif d[matrix,row,value] == d_max:
                
                f[matrix,row,value] = 100
             
                
            
f         

array([[[ 25.,  25.,  25.,  75.,  75.],
        [ 25.,  75.,  75.,  75.,  25.],
        [ 75.,  25.,  75.,  25.,  25.]],

       [[ 25.,  25.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,   0., 100.],
        [ 75.,  25.,  75.,  75.,  25.]]])